---
title: 'Stat 637 Project Proposal: International Travel Controls'
author: "Skyler Gray"
date: "November 16, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The pandemic has hit countries really hard. Economies have suffered and some forms of economic commerce have been at a halt for some time. With the pandemic continuing, vacationers all around the globe have been wondering: When will I be able to travel to x country?

My family purchased tickets to travel to Taiwan at the end of April 2022. At the time we purchased the tickets, we reckoned the pandemic would be over by then. Seeing as it has not ended yet, we are itching to estimate whether there is any reasonable chance that Taiwan will open its borders to tourists by April 2022.

The data for this analysis comes mainly from the Oxford COVID-19 Government Response Tracker (<https://doi.org/10.1038/s41562-021-01079-8>) through the Global Change Data Lab's **Our World in Data** project website (<https://ourworldindata.org/coronavirus>). This data contains ordinal data on the daily international travel controls during the COVID-19 pandemic for around 180 different countries. The responses from lowest to highest intensity are "No measures," "Screening," "Quarantine from high-risk regions," "Ban from high-risk regions," and "Total border closure." Additional data on monthly deaths or new cases and vaccination rate by country will also come through this site.

The chief question I hope to answer is the probability that Taiwan's international travel policy is less than or equal to "Screening." Additional questions may be whether there is a significant difference in travel controls among different continents and whether the number of COVID-related deaths in a month or the vaccination rate in a country significantly affect travel policy.

I plan to answer these questions by modeling my ordinal data using a latent variable Bayesian probit model. Let $Y_{ij}$ be the international travel control level of country $i$ on month $j$, where $j$ is the number of months after December 2020. Then

\begin{align*}
  Y_{ij} &= k \text{   if } \delta_{k-1} < Z_{ij} \le \delta_k \\
  Z_{ij} &= X_{ij}\beta + \epsilon_{ij} \\
  \epsilon &\sim N(0, V),
\end{align*}

where V is a block-diagonal AR(2) covariance matrix blocked by country and

\begin{align*}
  X_{ij}\beta = \beta_0 &+ ContNA_i\beta_1 + ContEU_i\beta_2 \\
                        &+ ContAS_i\beta_3 + ContSA_i\beta_4 \\
                        &+ ContOC_i\beta_5 + GDP_i\beta_6 \\
                        &+ PopDens_i\beta_7 + Deaths_{ij}\beta_8 \\
                        &+ VaccineRate_{ij}\beta_9
\end{align*}
